<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> new page' => '<strong>Vytvořit</strong> nový prostor',
    '<strong>Manage</strong> members' => '<strong>Spravovat</strong> členy',
    '<strong>Members</strong>' => '<strong>Členové</strong>',
    '<strong>Security</strong> settings' => '<strong>Bezpečnostní</strong> nastavení',
    '<strong>Page</strong> Modules' => '<strong>Moduly</strong> prostoru',
    '<strong>Page</strong> settings' => 'Nastavení <strong>prostorů</strong> ',
    'Actions' => 'Akce',
    'Activated' => 'Aktivováno',
    'Add <strong>Modules</strong>' => 'Přidat <strong>Moduly</strong>',
    'Advanced access settings' => 'Pokročilá nastavení přístupu a viditelnosti',
    'Archive' => 'Archivovat',
    'Are you sure, that you want to delete this page? All published content will be removed!' => 'Opravdu chcete smazat tento prostor? Veškerý jeho obsah bude smazán!',
    'Are you sure? *ALL* module data for this page will be deleted!' => 'Jste si opravdu jistí? *VŠECHNA* data modulu k tomuto prostoru budou smazána!',
    'As owner of this page you can transfer this role to another administrator in page.' => 'Jako vlastník tohoto prostoru můžete tuto roli přenést na jiného administrátora v tomto prostoru.',
    'Cancel Membership' => 'Zrušit členství',
    'Choose if new content should be public or private by default' => 'Zvolte, zda má být nový obsah ve výchozím nastavení veřejný nebo soukromý',
    'Choose the kind of membership you want to provide for this workspace.' => 'Vyberte, jak se lze stát členem prostoru.',
    'Choose the security level for this workspace to define the visibleness.' => 'Vyberte, jakou má mít prostor viditelnost.',
    'Configure' => 'Nastavit',
    'Currently there are no modules available for this page!' => 'Momentálně zde nejsou žádné dostupné moduly pro tento prostor!',
    'Delete' => 'Smazat',
    'Disable' => 'Zakázat',
    'Don\'t receive notifications for new content' => 'Nepřijímá oznámení o novém obsahu',
    'Enable' => 'Povolit',
    'Enhance this page with modules.' => 'Zde můžete rozšířit tento prostor moduly.',
    'Hide posts on dashboard' => 'Skrýt příspěvky na nástěnce',
    'Members' => 'Členové',
    'Modules' => 'Moduly',
    'Next' => 'Další',
    'Owner' => 'Vlastník',
    'Pending Approvals' => 'Čeká na schválení',
    'Pending Invites' => 'Čekající pozvánky',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'Oprávnění jsou přiřazena různým uživatelským rolím. Chcete-li upravit oprávnění, vyberte roli uživatele, kterou chcete upravit, a změňte rozbalovací hodnotu daného oprávnění.',
    'Receive Notifications for new content' => 'Dostávat upozornění na nové příspěvky',
    'Role' => 'Role',
    'Security' => 'Zabezpečení',
    'Send & decline' => 'Odmítnout',
    'Show all' => 'Zobrazit vše',
    'Show posts on dashboard' => 'Zobrazit na nástěnce',
    'Page name' => 'Název prostoru',
    'Page owner' => 'Vlastník',
    'Stream (Default)' => 'Stream(Výchozí)',
    'The url contains illegal characters!' => 'Adresa URL obsahuje nepovolené znaky!',
    'This option will hide new content from this page at your dashboard' => 'Tato volba skryje nový obsah z tohoto prostoru na nástěnce',
    'This option will show new content from this page at your dashboard' => 'Tato volba zobrazí nový obsah z tohoto prostoru na nástěnce',
    'Transfer ownership' => 'Převést práva',
    'Unarchive' => 'Obnovit z archívu',
    'e.g. example for {baseUrl}/s/example' => 'například. pro {baseUrl} ',
    'never' => 'nikdy',
    'page description' => 'Popis prostoru',
    'the default start page of this page for members' => 'výchozí stránka tohoto prostoru pro členy',
    'the default start page of this page for visitors' => 'výchozí stránka tohoto prostoru pro návštěvníky',
    '-' => '',
    'Invited By' => '',
    'Please type the name of the page to proceed.' => '',
    'Remove from page' => '',
];
