<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-' => '-',
    '<strong>Create</strong> new page' => '<strong>Opprett</strong> ny gruppe',
    '<strong>Manage</strong> members' => '<strong>Vedlikehold</strong> av medlemmer',
    '<strong>Members</strong>' => '<strong>Medlemmer</strong>',
    '<strong>Security</strong> settings' => '<strong>Sikkerhetsinnstillinger</strong>',
    '<strong>Page</strong> Modules' => '<strong>Gruppemoduler</strong>',
    '<strong>Page</strong> settings' => '<strong>Gruppeinnstillinger</strong>',
    'Actions' => 'Handlinger',
    'Activated' => 'Aktivert',
    'Add <strong>Modules</strong>' => 'Legg til <strong>moduler</strong>',
    'Advanced access settings' => 'Avansert tilgangskontroll',
    'Archive' => 'Arkivér',
    'Are you sure, that you want to delete this page? All published content will be removed!' => 'Er du sikker på at du vil slette gruppen? Alt publisert innhold blir fjernet!',
    'Are you sure? *ALL* module data for this page will be deleted!' => 'Er du sikker? *ALLE* moduldata for denne gruppen vil fjernes!',
    'As owner of this page you can transfer this role to another administrator in page.' => 'Som eier av denne gruppen kan du overføre din rolle til en annen administrator i gruppen.',
    'Cancel Membership' => 'Avslutt medlemskap',
    'Choose if new content should be public or private by default' => 'Velg om nytt innhold skal være offentlig eller privat som standard',
    'Choose the kind of membership you want to provide for this workspace.' => 'Velg type medlemskap du vil tildele i denne gruppen.',
    'Choose the security level for this workspace to define the visibleness.' => 'Velg sikkerhetsnivå for denne gruppen for å definere synlighet.',
    'Configure' => 'Konfigurér',
    'Currently there are no modules available for this page!' => 'Akkurat nå er det ingen moduler tilgjengelig for denne gruppen!',
    'Delete' => 'Slett',
    'Disable' => 'Deaktivér',
    'Don\'t receive notifications for new content' => 'Ikke motta varsel for nytt innhold.',
    'Enable' => 'Aktivér',
    'Enhance this page with modules.' => 'Utvid gruppen med moduler.',
    'Hide posts on dashboard' => 'Skjul innlegg i oversikten',
    'Members' => 'Medlemmer',
    'Modules' => 'Moduler',
    'Next' => 'Neste',
    'Owner' => 'Eier',
    'Pending Approvals' => 'Ventende Godkjenninger',
    'Pending Invites' => 'Ventende Invitasjoner',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'Tilgangsrettigheter settes for forskjellige brukerroller. For å redigere rettigheter, velg brukerrollen du ønsker å endre, og så endre verdien for den valgte rettigheten i nedtrekkslisten.',
    'Receive Notifications for new content' => 'Motta varsel for nytt innhold',
    'Remove from page' => 'Fjern fra gruppe',
    'Role' => 'Rolle',
    'Security' => 'Sikkerhet',
    'Send & decline' => 'Send & avvis',
    'Show all' => 'Vis alt',
    'Show posts on dashboard' => 'Vis innlegg i oversikten',
    'Page name' => 'Gruppenavn',
    'Page owner' => 'Gruppens eier',
    'Stream (Default)' => 'Nyhetsstrøm (Standard)',
    'The url contains illegal characters!' => 'Linken inneholder ugyldige tegn!',
    'This option will hide new content from this page at your dashboard' => 'Dette valget vill skjule nye innlegg fra denne gruppen i din oversikt',
    'This option will show new content from this page at your dashboard' => 'Dette valget vill vise nye innlegg fra denne gruppen i din oversikt',
    'Transfer ownership' => 'Overfør eierskap',
    'Unarchive' => 'Ta ut fra arkiv',
    'e.g. example for {baseUrl}/s/example' => 'f.eks. eksempel for {baseUrl}/s/eksempel',
    'never' => 'aldri',
    'page description' => 'Gruppebeskrivelse',
    'the default start page of this page for members' => 'standard startside for denne gruppens brukere',
    'the default start page of this page for visitors' => 'standard startsiden for denne gruppens gjester',
    'Invited By' => '',
    'Please type the name of the page to proceed.' => '',
];
