<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Page has been archived' => '',
    'Page has been unarchived' => '',
    'Whenever a page is archived.' => '',
    'Whenever a page is unarchived.' => '',
    'Page member joined' => 'Pridružio se član prostora',
    'Page member left' => 'Član prostora je otišao',
    'Whenever a member leaves one of your pages.' => 'Kad god član napušta jedan od vaših prostora.',
    'Whenever a new member joined one of your pages.' => 'Kad god se novi član pridruži jednom od vaših prostora.',
];
