<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-' => '-',
    '<strong>Create</strong> new page' => '<strong>Luo</strong> uusi sivu',
    '<strong>Manage</strong> members' => '<strong>Hallinnoi</strong> sivun jäseniä',
    '<strong>Members</strong>' => '<strong>Jäsenet</strong>',
    '<strong>Security</strong> settings' => '<strong>Suojaus</strong> asetukset',
    '<strong>Page</strong> Modules' => '<strong>Sivun</strong> Laajennukset',
    '<strong>Page</strong> settings' => '<strong>Sivun</strong> asetukset',
    'Actions' => 'Toiminnot',
    'Activated' => 'Aktivoitu',
    'Add <strong>Modules</strong>' => 'Lisää <strong>Laajennuksia</strong>',
    'Advanced access settings' => 'Lisäasetukset',
    'Archive' => 'Arkisto',
    'Are you sure, that you want to delete this page? All published content will be removed!' => 'Oletko varma, että haluat poistaa tämän sivun? Kaikki julkaistu sisältö poistetaan!',
    'Are you sure? *ALL* module data for this page will be deleted!' => 'Oletko varma? *KAIKKI* tämän laajenuksen tiedot poistetaan!',
    'As owner of this page you can transfer this role to another administrator in page.' => 'Tämän tilan omistajana voit siirtää tämän tehtävän toiselle ylläpitäjälle tällä sivulla.',
    'Cancel Membership' => 'Peruuta jäsenyys',
    'Choose if new content should be public or private by default' => 'Valitse, onko uusi sisältö oletuksena julkinen vai yksityinen',
    'Choose the kind of membership you want to provide for this workspace.' => 'Valitse millaiset jäsenyydet holuat sivulle.',
    'Choose the security level for this workspace to define the visibleness.' => 'Valitse sivun turvallisuustaso määrittääksesi näkyvyyden.',
    'Configure' => 'Määritä',
    'Currently there are no modules available for this page!' => 'Tällä sivulla ei tällä hetkellä ole laajennuksia!',
    'Delete' => 'Poista',
    'Disable' => 'Poista käytöstä',
    'Don\'t receive notifications for new content' => 'En halua ilmoituksia uudesta sisällöstä',
    'Enable' => 'Ota käyttöön',
    'Enhance this page with modules.' => 'Paranna tätä sivua laajennuksia.',
    'Hide posts on dashboard' => 'Piilota viestit hallintapaneelissa',
    'Invited By' => 'Kutsunut',
    'Members' => 'Jäsenet',
    'Modules' => 'Laajennukset',
    'Next' => 'Seuraava',
    'Owner' => 'Omistaja',
    'Pending Approvals' => 'Odottaa hyväksyntää',
    'Pending Invites' => 'Odottavat kutsut',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'Käyttöoikeudet on määritetty eri käyttäjärooleille. Voit muokata lupaa valitsemalla käyttäjänrooli, jota haluat muokata ja muuttaa käyttäjien rooleja.',
    'Receive Notifications for new content' => 'Vastaanota ilmoituksia uudesta sisällöstä',
    'Remove from page' => 'Poista sivulta',
    'Role' => 'Rooli',
    'Security' => 'Turvallisuus',
    'Send & decline' => 'Lähtä &amp; tallenna',
    'Show all' => 'Näytä kaikki',
    'Show posts on dashboard' => 'Näytä julkaisut työpöydällä',
    'Page name' => 'Sivun nimi',
    'Page owner' => 'Sivun omistaja',
    'Stream (Default)' => 'Etusivu (Oletus)',
    'The url contains illegal characters!' => 'linkki sisältää laittomia merkkejä!',
    'This option will hide new content from this page at your dashboard' => 'Tämä vaihtoehto piilottaa uuden sisällön työpöydältäsi',
    'This option will show new content from this page at your dashboard' => 'Tämä vaihtoehto näyttää uuden sisällön työpöydältäsi',
    'Transfer ownership' => 'Siirrä omistajuus',
    'Unarchive' => 'Poista arkistosta',
    'e.g. example for {baseUrl}/s/example' => 'esim. esimerkki {baseUrl} esimerkille',
    'never' => 'Ei koskaan',
    'page description' => 'sivun kuvaus',
    'the default start page of this page for members' => 'Sivu joka näkyy jäsenille ensimmäisenä',
    'the default start page of this page for visitors' => 'Sivu joka näkyy vierailioille ensimmäisenä',
    'Please type the name of the page to proceed.' => '',
];
