<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Page has been archived' => 'تم أرشفة الفضاء',
    'Page has been unarchived' => 'تم إخراج الفضاء من الأرشيف',
    'Page member joined' => 'انضم عضو الفضاء',
    'Page member left' => 'غادر عضو الفضاء',
    'Whenever a member leaves one of your pages.' => 'كلما غادر عضو واحد من مساحاتك.',
    'Whenever a new member joined one of your pages.' => 'كلما انضم عضو جديد إلى أحد مساحاتك.',
    'Whenever a page is archived.' => 'عندما يتم أرشفة مساحة.',
    'Whenever a page is unarchived.' => 'كلما كانت المساحة غير مؤرشفة.',
];
