<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Security</strong> settings' => '<strong>الأمان</strong> الاعدادات
',
    'Activated' => 'تم التفعيل',
    'Configure' => 'إعدادات',
    'Delete' => 'حذف',
    'Disable' => 'إلغاء التفعيل',
    'Enable' => 'تفعيل',
    'Members' => 'الأعضاء',
    'Modules' => 'الموديل',
    'Next' => 'التالي',
    'Security' => 'الأمان',
    'Unarchive' => 'إلغاء وضع الأرشيف',
    '-' => '-',
    '<strong>Create</strong> new page' => 'مساحة جديدة <strong>خلق</strong>',
    '<strong>Manage</strong> members' => 'أفراد <strong>يدير</strong>',
    '<strong>Members</strong>' => '<strong>أفراد</strong>',
    '<strong>Page</strong> Modules' => '<strong>مساحة</strong> الوحدات',
    '<strong>Page</strong> settings' => '<strong>مساحة</strong> الإعدادات',
    'Actions' => 'الإجراءات',
    'Add <strong>Modules</strong>' => 'أضف <strong>الوحدات</strong>',
    'Advanced access settings' => 'إعدادات الوصول المتقدمة',
    'Archive' => 'أرشيف',
    'Are you sure, that you want to delete this page? All published content will be removed!' => 'هل أنت متأكد أنك تريد حذف هذه المساحة؟ ستتم إزالة كل المحتوى المنشور!',
    'Are you sure? *ALL* module data for this page will be deleted!' => 'هل أنت واثق؟ * سيتم حذف بيانات * جميع * لهذه المساحة!',
    'As owner of this page you can transfer this role to another administrator in page.' => 'بصفتك مالك هذه المساحة ، يمكنك نقل هذا الدور إلى مسؤول آخر في الفضاء.',
    'Cancel Membership' => 'إلغاء العضوية',
    'Choose if new content should be public or private by default' => 'اختر ما إذا كان المحتوى الجديد يجب أن يكون عامًا أو خاصًا بشكل افتراضي',
    'Choose the kind of membership you want to provide for this workspace.' => 'اختر نوع العضوية التي تريد توفيرها لمساحة العمل هذه.',
    'Choose the security level for this workspace to define the visibleness.' => 'اختر مستوى الأمان لمساحة العمل هذه لتحديد مدى الرؤية.',
    'Currently there are no modules available for this page!' => 'حاليا لا توجد وحدات متاحة لهذه المساحة!',
    'Don\'t receive notifications for new content' => 'لا تتلقى إشعارات للمحتوى الجديد',
    'Enhance this page with modules.' => 'تعزيز هذه المساحة مع الوحدات النمطية.',
    'Hide posts on dashboard' => 'إخفاء المشاركات في لوحة القيادة',
    'Invited By' => 'بدعوة من',
    'Owner' => 'مالك',
    'Pending Approvals' => 'الموافقات المعلقة',
    'Pending Invites' => 'الدعوات المعلقة',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'يتم تعيين الأذونات لأدوار المستخدم المختلفة. لتحرير إذن ، حدد دور المستخدم الذي تريد تحريره وقم بتغيير القيمة المنسدلة للإذن المحدد.',
    'Please type the name of the page to proceed.' => 'يرجى كتابة اسم المساحة للمتابعة.',
    'Receive Notifications for new content' => 'تلقي الإخطارات للمحتوى الجديد',
    'Remove from page' => 'إزالة من الفضاء',
    'Role' => 'وظيفة',
    'Send & decline' => 'إرسال و رفض',
    'Show all' => 'عرض الكل',
    'Show posts on dashboard' => 'عرض المشاركات على لوحة القيادة',
    'Page name' => 'اسم المساحة',
    'Page owner' => 'مالك المساحة',
    'Stream (Default)' => 'دفق (افتراضي)',
    'The url contains illegal characters!' => 'يحتوي العنوان على أحرف غير قانونية!',
    'This option will hide new content from this page at your dashboard' => 'سيؤدي هذا الخيار إلى إخفاء المحتوى الجديد من هذه المساحة في لوحة التحكم',
    'This option will show new content from this page at your dashboard' => 'سيعرض هذا الخيار محتوى جديدًا من هذه المساحة في لوحة التحكم',
    'Transfer ownership' => 'نقل الملكية',
    'e.g. example for {baseUrl}/s/example' => 'على سبيل المثال مثال لـ {baseUrl} / s / example',
    'never' => 'أبدا',
    'page description' => 'وصف المساحة',
    'the default start page of this page for members' => 'صفحة البداية الافتراضية لهذه المساحة للأعضاء',
    'the default start page of this page for visitors' => 'صفحة البداية الافتراضية لهذه المساحة للزوار',
];
