<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Receive Notifications of Page Membership events.' => 'تلقي إخطارات أحداث عضوية الفضاء.',
    'Page Membership' => 'عضوية الفضاء',
    'View Online' => 'مشاهدة حية',
    'You were added to Page {spaceName}' => 'تمت إضافتك إلى Page {spaceName}',
    '{displayName} accepted your invite for the page {spaceName}' => 'قبل {displayName} دعوتك للمساحة {spaceName}',
    '{displayName} approved your membership for the page {spaceName}' => 'وافق {displayName} على عضويتك في المساحة {spaceName}',
    '{displayName} changed your role to {roleName} in the page {spaceName}.' => 'قام {displayName} بتغيير دورك إلى {roleName} في الفضاء {spaceName}.',
    '{displayName} declined your invite for the page {spaceName}' => 'رفض {displayName} دعوتك للمساحة {spaceName}',
    '{displayName} declined your membership request for the page {spaceName}' => 'رفض {displayName} طلب عضويتك للمساحة {spaceName}',
    '{displayName} invited you to the page {spaceName}' => 'دعاك {displayName} إلى الفضاء {spaceName}',
    '{displayName} requests membership for the page {spaceName}' => 'يطلب {displayName} عضوية للمساحة {spaceName}',
    '{displayName} revoked your invitation for the page {spaceName}' => '{displayName} أبطل دعوتك للمساحة {spaceName}',
];
