<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-' => '-',
    '<strong>Create</strong> new page' => '<strong>Yeni</strong> mekan oluştur',
    '<strong>Manage</strong> members' => 'Üyeleri yönet',
    '<strong>Members</strong>' => '<strong>Üyeler</strong>',
    '<strong>Security</strong> settings' => '<strong>Güvenlik</strong> ayarları',
    '<strong>Page</strong> Modules' => '<strong>Mekan</strong> Modülleri',
    '<strong>Page</strong> settings' => '<strong>Mekan</strong> ayarları',
    'Actions' => 'Eylemler',
    'Activated' => 'Aktive edildi',
    'Add <strong>Modules</strong>' => '<strong>Modül</strong> ekle',
    'Advanced access settings' => 'Gelişmiş erişim ayarları ',
    'Archive' => 'Arşiv',
    'Are you sure, that you want to delete this page? All published content will be removed!' => 'Tüm yayınlanan içerikler silinecektir! Bu mekanı silmek istediğinizden emin misiniz?',
    'Are you sure? *ALL* module data for this page will be deleted!' => 'Emin misiniz? Bu alan için *TÜM * modül verileri silinecek!',
    'As owner of this page you can transfer this role to another administrator in page.' => 'Bu sayfanın sahibi olarak sayfanızdaki başka bir kullanıcıya yönetici rolünüzü aktarabilirsiniz.',
    'Cancel Membership' => 'Üyeliği iptal et',
    'Choose if new content should be public or private by default' => 'Yeni içeriğin varsayılan olarak genel mi yoksa özel mi olacağını seçin',
    'Choose the kind of membership you want to provide for this workspace.' => 'Bu çalışma alanı için sağlamak istediğiniz üyelik türünü seçin.',
    'Choose the security level for this workspace to define the visibleness.' => 'Görünürlüğü tanımlamak için bu çalışma alanının güvenlik seviyesini seçin.',
    'Configure' => 'Yapılandırma',
    'Currently there are no modules available for this page!' => 'Şu anda bu mekanda hiçbir modül bulunmuyor!',
    'Delete' => 'Sil',
    'Disable' => 'Devre dışı',
    'Don\'t receive notifications for new content' => 'Bildirimleri kapat',
    'Enable' => 'Etkin',
    'Enhance this page with modules.' => 'Modüller ile bu alanı geliştirin.',
    'Hide posts on dashboard' => 'Mesajları gizle',
    'Members' => 'Üyeler',
    'Modules' => 'Modüller',
    'Next' => 'Devam',
    'Owner' => 'Yönetici',
    'Pending Approvals' => 'Bekleyen Onaylar',
    'Pending Invites' => 'Bekleyen Davetler',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'İzinler farklı kullanıcı rollerine atanmıştır. Bir izni düzenlemek için, düzenlemek istediğiniz kullanıcı rolünü seçin ve verilen izne uygun değeri değiştirin.',
    'Receive Notifications for new content' => 'Bildirimleri aç',
    'Remove from page' => 'Mekandan kaldır',
    'Role' => 'Rol',
    'Security' => 'Güvenlik',
    'Send & decline' => 'Gönder ve Kabul etme',
    'Show all' => 'Hepsini Göster',
    'Show posts on dashboard' => 'Mesajları göster',
    'Page name' => 'Mekan adı',
    'Page owner' => 'Mekan sahibi',
    'Stream (Default)' => 'Yayın (Varsayılan)',
    'The url contains illegal characters!' => 'Url geçersiz karakterler içeriyor!',
    'This option will hide new content from this page at your dashboard' => 'Bu seçenek, bu mekandaki yeni içeriği kontrol panelinizde gizler.',
    'This option will show new content from this page at your dashboard' => 'Bu seçenek, bu mekandaki yeni içeriği kontrol panelinizde gösterir.',
    'Transfer ownership' => 'Mülkiyet transfer',
    'Unarchive' => 'Arşivden çıkar',
    'e.g. example for {baseUrl}/s/example' => 'ör: {baseUrl}/s/örnek',
    'never' => 'asla',
    'page description' => 'mekan açıklaması',
    'the default start page of this page for members' => 'sayfa üyeleri için gösterilecek varsayılan giriş sayfası',
    'the default start page of this page for visitors' => 'misafirler için gösterilecek varsayılan giriş sayfası',
    'Invited By' => '',
    'Please type the name of the page to proceed.' => '',
];
